apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jys2vdqpf-go 
  janus-idp.io/tekton: jys2vdqpf-go
  backstage.io/kubernetes-id: jys2vdqpf-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jys2vdqpf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml